import os
import json
from datetime import datetime
from pathlib import Path
from typing import Dict, Optional, List


def generate_referral_summary(
    clinical_data: Dict[str, any],
    risk_assessment: Dict[str, any],
    trends: Optional[List[str]] = None,
    symptoms: Optional[Dict[str, bool]] = None
) -> str:
    patient_name = clinical_data.get('patient_name', 'Unknown')
    patient_id = clinical_data.get('patient_id', 'N/A')
    patient_age = clinical_data.get('age', 'Unknown')
    visit_date = clinical_data.get('date', datetime.now().strftime("%Y-%m-%d"))
    
    lines = [
        "=" * 60,
        "       ANTENATAL CARE REFERRAL SUMMARY",
        "=" * 60,
        f"Patient Name: {patient_name}",
        f"Patient ID:   {patient_id}",
        f"Age:          {patient_age}",
        f"Visit Date:   {visit_date}",
        f"Risk Tier:    {risk_assessment['risk_level'].upper()} (Score: {risk_assessment['risk_score']})",
        "",
        "-" * 60,
        "CLINICAL VALUES:",
        "-" * 60,
    ]
    
    lines.extend(_format_clinical_values(clinical_data))
    
    if symptoms:
        lines.append("")
        lines.append("-" * 60)
        lines.append("PATIENT-REPORTED SYMPTOMS:")
        lines.append("-" * 60)
        lines.extend(_format_symptoms(symptoms))
    
    if trends:
        lines.append("")
        lines.append("-" * 60)
        lines.append("LONGITUDINAL TRENDS:")
        lines.append("-" * 60)
        for trend in trends:
            lines.append(f"  {trend}")
    
    lines.append("")
    lines.append("-" * 60)
    lines.append("RISK FACTORS:")
    lines.append("-" * 60)
    for factor in risk_assessment['risk_factors']:
        lines.append(f"  * {factor}")
    
    lines.append("")
    lines.append("-" * 60)
    lines.append("CLINICAL RECOMMENDATIONS:")
    lines.append("-" * 60)
    for i, rec in enumerate(risk_assessment['recommendations'], 1):
        lines.append(f"  {i}. {rec}")
    
    lines.append("")
    lines.append("-" * 60)
    lines.append(f"ASSESSMENT: {risk_assessment['summary']}")
    lines.append("-" * 60)
    lines.append("")
    lines.append(f"QR Code: [referral_qr_{patient_id}.png]")
    lines.append("Generated by: PregnancyBridge v1.0")
    lines.append(f"Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("=" * 60)
    
    return "\n".join(lines)


def save_summary_to_file(summary: str, patient_name: str, output_dir: str = "summaries") -> str:
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    
    safe_name = "".join(c for c in patient_name if c.isalnum() or c in (' ', '_')).rstrip()
    safe_name = safe_name.replace(' ', '_')
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    
    filename = f"referral_{safe_name}_{timestamp}.txt"
    filepath = os.path.join(output_dir, filename)
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(summary)
    
    return filepath


def save_clinical_record_json(
    clinical_data: Dict[str, any],
    risk_assessment: Dict[str, any],
    output_dir: str = "data"
) -> str:
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    
    record = {
        "patient_name": clinical_data.get('patient_name'),
        "patient_id": clinical_data.get('patient_id'),
        "visit_date": clinical_data.get('date', datetime.now().strftime("%Y-%m-%d")),
        "clinical_values": {
            "hemoglobin": clinical_data.get('hemoglobin'),
            "bp_systolic": clinical_data.get('bp_systolic'),
            "bp_diastolic": clinical_data.get('bp_diastolic'),
            "gestational_age": clinical_data.get('gestational_age'),
            "proteinuria": clinical_data.get('proteinuria'),
            "weight": clinical_data.get('weight'),
            "fundal_height": clinical_data.get('fundal_height'),
            "edema": clinical_data.get('edema'),
        },
        "risk_assessment": {
            "level": risk_assessment['risk_level'],
            "score": risk_assessment['risk_score'],
            "factors": risk_assessment['risk_factors'],
            "recommendations": risk_assessment['recommendations'],
        },
        "timestamp": datetime.now().isoformat()
    }
    
    patient_name = clinical_data.get('patient_name', 'unknown')
    safe_name = "".join(c for c in patient_name if c.isalnum() or c in (' ', '_')).rstrip().replace(' ', '_')
    filename = f"record_{safe_name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    filepath = os.path.join(output_dir, filename)
    
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(record, f, indent=2, ensure_ascii=False)
    
    return filepath


def _format_clinical_values(data: Dict[str, any]) -> List[str]:
    hb = data.get('hemoglobin')
    bp_sys = data.get('bp_systolic')
    bp_dia = data.get('bp_diastolic')
    ga = data.get('gestational_age')
    protein = data.get('proteinuria')
    weight = data.get('weight')
    fh = data.get('fundal_height')
    edema = data.get('edema')
    
    bp_str = f"{bp_sys}/{bp_dia}" if bp_sys and bp_dia else "N/A"
    edema_str = "Present" if edema else "Absent" if edema is False else "N/A"
    
    return [
        f"  Hemoglobin:       {hb or 'N/A'} g/dL",
        f"  Blood Pressure:   {bp_str} mmHg",
        f"  Gestational Age:  {ga or 'N/A'} weeks",
        f"  Proteinuria:      {protein or 'N/A'}",
        f"  Weight:           {weight or 'N/A'} kg",
        f"  Fundal Height:    {fh or 'N/A'} cm",
        f"  Edema:            {edema_str}",
    ]


def _format_symptoms(symptoms: Dict[str, bool]) -> List[str]:
    present_symptoms = [
        symptom.replace('_', ' ').title()
        for symptom, present in symptoms.items()
        if present
    ]
    
    if present_symptoms:
        return [f"  + {symptom}" for symptom in present_symptoms]
    
    return ["  No significant symptoms reported"]
